---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky-redis
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: redis
      version: 16.8.9
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: Europe/Paris
    image:
      registry: ghcr.io
      repository: zcube/bitnami-compat/redis
      tag: 6.2
    master:
      persistence:
        enabled: false
      resources:
        requests:
          cpu: 250m
          memory: 16Mi
        limits:
          cpu: 500m
          memory: 32Mi
    replica:
      replicaCount: 1
      persistence:
        enabled: false
      autoscaling:
        enabled: True
        targetCPU: 50
        targetMemory: 75
      resources:
        requests:
          cpu: 250m
          memory: 16Mi
        limits:
          cpu: 500m
          memory: 32Mi
    auth:
      enabled: false
      sentinel: false
    sentinel:
      enabled: True
      image:
        registry: ghcr.io
        repository: zcube/bitnami-compat/redis-sentinel
        tag: 6.2
      resources:
        requests:
          cpu: 125m
          memory: 8Mi
        limits:
          cpu: 250m
          memory: 16Mi
    metrics:
      enabled: false
      image:
        registry: ghcr.io
        repository: zcube/bitnami-compat/redis-exporter
        tag: 1
