---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky-redis
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: redis
      version: 16.4.3
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: Europe/Paris
    image:
      registry: ghcr.io
      repository: zcube/bitnami-compat/redis
      tag: 6.2
    master:
      persistence:
        enabled: false
    replica:
      replicaCount: 0
      persistence:
        enabled: false
    auth:
      enabled: false