apiVersion: apps/v1
kind: Deployment
metadata:
  name: earnapp2
  namespace: earn
  labels:
    app: earnapp
spec:
  selector:
    matchLabels:
      app: earnapp
      tier: frontend
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: earnapp
        tier: frontend
    spec:
      containers:
      - name: earnapp
        image: fazalfarhan01/earnapp:lite
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "0.5"
            memory: 128Mi
          requests:
            cpu: "0.1"
            memory: 16Mi
        env:
        - name: EARNAPP_UUID
          value: ${SECRET_EARNAPP_2}