---
kubernetes:
  children:
    master:
      hosts:
        kmas1:
          ansible_host: 10.1.0.31
    worker:
      hosts:
        knod1:
          ansible_host: 10.1.0.41
        knod2:
          ansible_host: 10.1.0.42
        knod3:
          ansible_host: 10.1.0.43
