---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/external-dns
      chart: external-dns
      version: 1.7.1
      sourceRef:
        kind: HelmRepository
        name: external-dns-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
    - name: metallb
      namespace: metallb-system
    - name: traefik
      namespace: networking
  values:
    interval: 5m
    logLevel: debug
    provider: cloudflare
    env:
      - name: CF_API_EMAIL
        value: ${SECRET_CLOUDFLARE_EMAIL}
      - name: CF_API_KEY
        value: ${SECRET_CLOUDFLARE_APKI_KEY}
    policy: sync
    sources:
      - ingress
    txtPrefix: "k8s."
    txtOwnerId: "default"
    domainFilters:
      - "${SECRET_DOMAIN}"
    resources:
      requests:
        memory: 100Mi
        cpu: 25m
      limits:
        memory: 250Mi
