# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:pUBoMiJBdNrsDaBHYXj3WAjkkQxz7aKeiR2WG6o=,iv:a4+OUH6JHnl54Nm8gOmmrbDJ4YFcMu9dFjgd5iZZpHE=,tag:q21ZYBD6TaNluav3DUr0GA==,type:str]
    api-key: ENC[AES256_GCM,data:6qCo+AGcvyf4bjEbtP1tkY8Pbz4zKmQk7n3ptbs1CX1RGHZiNA==,iv:koHJkoN/d9qtA3BvLor+UjGSaNJiplpTQmvvI2rE3EU=,tag:sTdkZky2bIXpUgxmemN0xA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVDZEMjFqZ0I4c2ZPaEdP
            bDBReW9pZXNPYUZ6NitnZnE4RHRtVGV2Z0dZCld5K0k5VTQ1TWh6eTlNZFFMTmpM
            bGw0UUhPcG5zdGY1ZXYwTlNKSWE0ak0KLS0tIDJQaCtlUDR3d3cyNmxyNUYybzhj
            RnQzMHVSVk5nelRGcWNiT1RWNTlWTmMK441twILbHx26KRczrAPhjMNRuddZwh1/
            F6jjQhiRksI11RPw1VLE8yq2Ah6zFrHUZGoqZFBNmwqVBX8VgXbheQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-19T16:13:02Z"
    mac: ENC[AES256_GCM,data:duqRJe2SA4rehqw3gdKaMR8T2cfLS+48xAYs+qXHXK7uGYHd2o8MG5uKOILFR2S29vbferBiM26MYhBbpIjOrDoEUpZwljb2f5NAVyb2NxjQUGDlORZI+nj8IbvJpvSOuKpz1EyTa1+lmBwVdkfOaH1kCRY5LgFCoEbQHS45K6M=,iv:1Sv4W39NdCnU9JE8pWvOZ6eF0qUUs6qiTgpPG+QCAT4=,tag:9NI//VEelP7EdYNmWd695A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
