---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Europe/Paris
  METALLB_LB_RANGE: 10.1.0.100-10.1.0.200
  METALLB_K8S_GATEWAY_ADDR: 10.1.0.101
  METALLB_TRAEFIK_ADDR: 10.1.0.100
