---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Europe/Paris
  METALLB_LB_RANGE: 10.0.1.100-10.0.1.200
  METALLB_K8S_GATEWAY_ADDR: 10.0.1.101
  METALLB_INGRESS_ADDR: 10.0.1.100
