---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: networking
spec:
  interval: 20m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: blocky
      version: ">=5.0.0"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: Europe/Paris
    controller:
      replicas: 2
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - blocky
          topologyKey: "kubernetes.io/hostname"
    service:
      dns-tcp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 10.1.0.101
        annotations:
          metallb.universe.tf/allow-shared-ip: blocky
      dns-udp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 10.1.0.101
        annotations:
          metallb.universe.tf/allow-shared-ip: blocky
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 50m
        memory: 275Mi
    config: |
      upstream:
        externalResolvers:
        - https://dns1.nextdns.io/4838af
        - https://dns2.nextdns.io/4838af
        - tcp-tls:4838af.dns1.nextdns.io:853
        - tcp-tls:4838af.dns2.nextdns.io:853
        - 46.182.19.48
        - 80.241.218.68
        - tcp-tls:fdns1.dismail.de:853
        - https://dns.digitale-gesellschaft.ch/dns-query
        - udp:208.67.220.220
        - udp:208.67.220.222
      conditional:
        mapping:
          ${SECRET_DOMAIN}: udp:10.1.0.4
          0.1.10.in-addr.arpa: udp:10.1.0.4
          1.1.10.in-addr.arpa: udp:10.1.0.4
      blocking:
        blackLists:
          ads:
            # https://oisd.nl/
            - https://dbl.oisd.nl/
            - https://raw.githubusercontent.com/ookangzheng/dbl-oisd-nl/master/dbl.txt
            - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
            - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
            # https://mirror1.malwaredomains.com/files/justdomains
            - http://sysctl.org/cameleon/hosts
            # https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
            - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
          special:
            - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts
        clientGroupsBlock:
          default:
          - ads
          - special
      logLevel: info
      httpPort: 4000
      clientLookup:
        upstream: tcp+udp:10.1.0.4
      prometheus:
        enable: true
        path: /metrics
