kind: Secret
ansible_user: ENC[AES256_GCM,data:o3Q=,iv:zyc8x3yE+UZYRfa4WeONdXBRj17tfOKYJgTJY/liMNY=,tag:LqROJ+vgnxwKpyBzcX2L2A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:UBxwmUHzgf8=,iv:kcM2gzBV33dE/51IEigPDbuCpMQJX2MUxyftPwjuCl4=,tag:ok/ggBN0UKA1yo/PgKci/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVnR2V2h1dnRzYzZDZmlB
            d2xybFJFMjg3VFdpOWJRM3ZzL2xQaitWN0E4CkVXTEtzTG5FRWdRN2xUc0ZYbFlh
            ck9KTjkwTEFBM2FwSVd4S0V0aTRweTAKLS0tIGY0S29iUWJYRDk0RC9sUTVBVzN5
            NnFOMHBLNmJ2cy9FUjRzekxGb0dQZEkKNpMAa2pu5cTP9Km9jf/n+i3a5Lcx0RUp
            1jrxLUjh6Yf/6jLvWtFGq8P4scP/ysogsfyzIYQBoaoI4anfIvB7Kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-24T15:00:07Z"
    mac: ENC[AES256_GCM,data:yWKhfUikAdf2Q9g8wex7m5zEktJUyVkj+rabYLRqDq6tqFuUlp029dcUcEZjc0iHsNl6fPMqHZnhj/ffrLAlDnXObt6r/xYHgtS0VpezLYUa4DoP4IDSy+TNrHEZqpGd+ZfcCzSXfhncON1OiAjabRA9RUHmhM+FM941KIADTT8=,iv:74mL9Y2Ehsg7PHVHV4+v6lWmQy1xREFGT0eXPutVCOQ=,tag:indZflDGteLtSaJxWovLDA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
