kind: Secret
ansible_user: ENC[AES256_GCM,data:odY=,iv:BCn73JUAMz2RLjLzd+cpAEtZEL04DsvEhFg0eod6xec=,tag:FW3ucXEoAr2OxyyqivPEqw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:oTXpL9YR8Uw=,iv:p7mBneSiZsmxQHs8sDVcGcpEVYgZw/stAkZqxy83mlU=,tag:8JeCO2cx4zgsCatJEt2C4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCT29xWkl3aXpYd0p2RUVN
            bkQxOWJjUTFRSEorM240WTBLOHZXMkFTWlhRCkRnY2JnVG5HQTZiUnZ4WEJNU0c2
            WStSUXB1RVRhaEhxTml6VkVpZ1NtSkEKLS0tICt5eDNTMVJXOTlQMllJUjBnb1Fr
            SE11eUloa3l0M2xwOTZHZWJhb0U1WFEKVJ/1x3lv48gO25GDzOvoDKSiGbeRYdjw
            oI++2gfcgDaIT+CzptPrz5HOPR4r1OsvatEezzki9YEhf5JesrCmyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-10T17:54:58Z"
    mac: ENC[AES256_GCM,data:jk+hWa0J8zLNpJzKUls8sw9QhN+unh2bN6lu0AeB3Xn8zsS0f6N5wCEZy29iR/kD8Mv+kzUdi3o+RvK/2h3ZTQrOKIMoibkP/TZeK/XQ8ItRS6Y1q2yDAWdgayfamhsoOURM4zOzQq7eeEr1sUhe606+FTZNu9xkU6IQNc5e5Vk=,iv:dU8c2O2S4TzunhZwmgYFKaE7dnLL8La25X0PckLiHBU=,tag:InyOkZ2WJS6JJLpobeS2EQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
