kind: Secret
ansible_user: ENC[AES256_GCM,data:5eI=,iv:U4IpaXFDKzrR5HbQWm57V1Jo5yYSaiMXf06yE8N892U=,tag:sK9yq3zXdidSW+sDz2YthQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ZYh3/N1sxYs=,iv:q2rOUmRPDP2BryQlZmHS+xH4gvbNZYJrGP60zB1ML2g=,tag:VB0Ja7VWnToOTPiUafdNuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNm1iUGZjL29keE8yaDRH
            N0JPcm01clFPNzB4Vjk2ZmJmdjJ1KzFmalZzCnJEV1RrazlrRDRlNDdtbytURHp3
            UmhDVitKVWlWZ0UzZGFVUmhkK3NVM0kKLS0tIGhRUnFYMTMrMUQ1QlNZUHQxQjVP
            TGlqWEZSZ1hPQ0YyN280czd0c3dHdkkKt5hgZGMp6BV1rr63HbYMugIYvSjGzExb
            7I1cruqkFVy9WUy2dW6hkPaBc3d/vYUj6Mbh3V1NYegb/69Ft4+z6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-10T17:54:58Z"
    mac: ENC[AES256_GCM,data:0YZm+7UeBQBRo5NwD8o/rnPBsek37zWHkaVusoDcteTnCxF66a0CABzPRReue16eNITtWs89OTfQky53fNLST9nl21DRplgKQK+PTj4KIV+SHpJXOD2A3pLunIFZ6PFzSN9diNigRTPPIwsAMTDf0+s9inbqLOu6JGWM2jTTmjk=,iv:r4z2hNKgY5p2ZRII/yJvhJVVax0BxCmXj44AUdWoZAk=,tag:D/0gZJjv+ON5/qsgFVVHFg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
