kind: Secret
ansible_user: ENC[AES256_GCM,data:Hds=,iv:ykAuJcJmuD6z3ngDcwxN1Xhhaqupd8C5ohxyGT5ubaU=,tag:sOLByznST1+0oVBkJdpcKA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:5Cwm7HYNQss=,iv:vmltbsqe/rg/dqiwGTTKw42wksA5/a7IXsbvstMZAAc=,tag:UYv7RK5GCdOVffhkXgtQ7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbzZVVUhoTGhqa1h5eDJ0
            M3BiUXRydDdMcndGbHRuRHZrd0sxekpHb3hrCmtUNWdVcFJocEFrUzdFS24xdlZv
            SU92SEt6MFRxc2RsWElKOHFJTlBtWFkKLS0tIHNpRXM4T3BwUGxkSlE0NW5DWlBs
            TEw0NkNDakE3emNtSU03dk41ZXhocUEKuc95gwGmh3LvdcSViLNmzjPeWhiKI7Q3
            2Fx8k4xhCh+FeE5dOtc6d8KpKjgx2/kV67z/G8Rb40iBGuhxb+dCgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-10T13:44:02Z"
    mac: ENC[AES256_GCM,data:+MXR8OyIeF41ZAIQMIyX4dF0VbmEZWCHjC1Q2A8nl5CrjzAZ8BLgPizfwUXynXXnMhzEuRqBLtfoOneihMyMxp5AdpDLA4F/kqHNZUp6pLd1ficZ2xPn4ly3FhA0n4F3bH+p9yr/nCBGgsfHS2FRLYKLNMwSQjReKzpKH7KFMvI=,iv:xZnzq6F9rbfqLnjOF/TC10pDMD3Jgvb0KRW/68yYArY=,tag:RhFVAEo40BYYK5UYp/lqNw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
