kind: Secret
ansible_user: ENC[AES256_GCM,data:heI=,iv:rpcSWohXxkEgqRhCt9A4nkJUN3e2wkSAQ/Xfep57rmw=,tag:2v76Sa0CC5IdOHqqF2U86w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:zSHodbOz8pE=,iv:n7iw+LZ+qJOJrhLWrLHAM4Koj2vXgZ5TTAsvRMUd9pI=,tag:7mMzl9yVQJlmgv00KFNRgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNGZLakc5dEJRdGt6RU1y
            MnY1UzR1ZnRwYUlpSmcvekZjMU04MjR2UnhRCnpYeDF0aTNJRnNLUHpwcGJDeTNp
            VGcxTXQ1VkEycG15dEtMdmhtNjFYVFUKLS0tICtBUW03K2xRTkFjbVRuZ04wRWdS
            eDNObGZvdnFnZGM2TTI4SmU4UWlDSG8KdSey+pILM0orhAQf+obhTX9MKGZdHq+S
            JPX6dBOv/gw2klIK9z7oLjP0UP1L9yO84xLPuB5pxJtGIjljcyxLsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-18T21:10:17Z"
    mac: ENC[AES256_GCM,data:lf6u02qpLaESlf0XHsPhtVNgx7Xdzu61CvTVmdo+Rbrh+yfoZRuRNlpilmf1pNHgKaTUZ6teFk2QGDygZCt+1jplFkn7BiaoadlC+4GEoE2unek1ouTdM70U4w4rS9qBlmTc7tlOP7vxsOalPgFOqCXU4nNS8glrpeJs7RTxvHc=,iv:iiKki7XfVZI4TflL2EpLRzleTbYnev66DiVImXDU7Fw=,tag:RuInlzlj7O1Vfn3K4IS2pw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
