kind: Secret
ansible_user: ENC[AES256_GCM,data:qfQ=,iv:kjjVD9LM2cT7VDUB+gav6fUhM+7To7e2ouyjYM6fGIM=,tag:mBSntiemboCBaBp08GqglA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:WfgGzte5a28=,iv:Iaz0/M+mqeH7jbvudI/lDOsc0mc31NSXwHY3RTJpakA=,tag:t6FdjKKBZn51wmDAA86WDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1UkI1amdMdWhQWG5OSS9N
            NnRjdkQ5SUp0WHU1d3J6emRHY0t2Z01nVmhFCm5yVkhGdU5HMDFOSU8yMHQrSWxE
            ZVFFVWg1WXBNb0d5VDl2RHFyZGxyLzAKLS0tIFBqT09qMEp3bzMvemJLN0ZYZWFD
            T3VwemQxWE43blpaOENqbzlJeHp6YmsKIw38ZV6kAx3Q0C2Ni856oOfuunu4O40T
            KBKmghqcT/t+0NsTkajh5emst51gqZBUDjedSS7Xx6GHF9t5jHTAtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-09T08:19:53Z"
    mac: ENC[AES256_GCM,data:TEzWb/At7VbqZd5ye2w6gY6fulw12TyF3kgStsnVcjJa/6j5CDOdOk1R1wXVKv0x6c+/pZPg9Tx/mhGU4g1xwbUX6LUTmsf5Eui9Gh4Qwp8+RAQKU6+ZukWGKffghS3Sm1T7bT6KLRl/umX9WDVWX2gCD9DjBU/WbDAYtfJXZCw=,iv:dRymAIpFGAfdF14zASoTdAGOzaBTkjdDT4BlJ18gyQI=,tag:M+V7w4ghZaZ9ltNNYaMHAg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
