# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:6jeEpFfCOv8NvopCRGLp,iv:Y7csI24iLhsvLhcFE2hrCF3qbndAAnLMa6AGygYiFUg=,tag:hCcB8guwh2LEk+wMZUgMIA==,type:str]
    SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:9WMKOXzY8EpZLw==,iv:4SKZe92y472EyJxlpm7IS8AoI7/UdY7AX+1FiO7KWy8=,tag:MI8Z5/k8iA/u+oSwlft6JA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:rE023QrXduCuul6Xrtdf+VJXCXJKT3hX5XofxI0=,iv:CPj5fJqSh2qjCxLCSdQDuyb0I+CSVOcq3UalyHWcUsM=,tag:M0UI/ammLoGJepkq1bc++g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTzRkdm1wWXhlY3E1UlJF
            cVRsS3dmSTFpN2E1VGRnVFpVbDVuQnFkRWdVCjZSaEozcXNjNitNYktSenpnYm5O
            QjNlcG84aDR2UzVtZzdKZHhiREJQS0kKLS0tIDRiMDBGbXQ5eERuS2VoTGc4RXBi
            R3dtWlVwbFZKbVlBVG5SYU1FUEVPNVEKcO+CMIm24g7BLVVRlBreYBTCeS8GNCJx
            coIxzkHBEOulIYY85tTPWs4E7piQvXND/1eKUMOsdseaq9CpPngBdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-13T17:44:13Z"
    mac: ENC[AES256_GCM,data:1/Mc1gGAH8cHWWjq4KN11ysDjIRGbyZ0JAWo8bXQXZBAQIR2wD+k5LO0QCh/qkfVe9Q1VpIearL7H6IlpMqkb5ThHfm9LxdcfcrmKQZJtMGyI8X4orVF8WiR4dQoH5ycVkgtOwMFEWStqcupiSzqDGGYJq7yPjAFP3SfYoTBPko=,iv:AWCly9WWTLA3Bd8UGCSyZnltzqXYyDU2fLzmW1iH47I=,tag:MQabMmj0fp6du80bXypRkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
