# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:6jeEpFfCOv8NvopCRGLp,iv:Y7csI24iLhsvLhcFE2hrCF3qbndAAnLMa6AGygYiFUg=,tag:hCcB8guwh2LEk+wMZUgMIA==,type:str]
    SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:9WMKOXzY8EpZLw==,iv:4SKZe92y472EyJxlpm7IS8AoI7/UdY7AX+1FiO7KWy8=,tag:MI8Z5/k8iA/u+oSwlft6JA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:rE023QrXduCuul6Xrtdf+VJXCXJKT3hX5XofxI0=,iv:CPj5fJqSh2qjCxLCSdQDuyb0I+CSVOcq3UalyHWcUsM=,tag:M0UI/ammLoGJepkq1bc++g==,type:str]
    SECRET_CLOUDFLARE_APKI_KEY: ENC[AES256_GCM,data:2dpfXf8k515MiE8yF9UGSkw3Cm1kge54xul0XHXhwWI6nVelfg==,iv:9geLjMdDeR7368jZ3aqrY+VdkvehJkW1tLGxgQ2KbcA=,tag:0dqmgOYlSpPpcq5QOYpqMQ==,type:str]
    SECRET_AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:pZkfQOG0NrRAUHeXnoHWHXKZ0ROofrU=,iv:wU6SLjfuK/Fqw+PFyCPWtQyQMyk+/+VwRV+Xitljptk=,tag:HeiaP13UoTRwyvDxeLrIkQ==,type:str]
    SECRET_AUTHENTIK_PG_PASSWORD: ENC[AES256_GCM,data:SjyxkG+dJWSECYyenPOZh4ggHja57Q==,iv:ZsGvXSqbypsYfU1dwH+jLaEvQmCNwcIk3dWwRj2iJOg=,tag:0OV/ugzgMdB3U8ywJHFlEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTzRkdm1wWXhlY3E1UlJF
            cVRsS3dmSTFpN2E1VGRnVFpVbDVuQnFkRWdVCjZSaEozcXNjNitNYktSenpnYm5O
            QjNlcG84aDR2UzVtZzdKZHhiREJQS0kKLS0tIDRiMDBGbXQ5eERuS2VoTGc4RXBi
            R3dtWlVwbFZKbVlBVG5SYU1FUEVPNVEKcO+CMIm24g7BLVVRlBreYBTCeS8GNCJx
            coIxzkHBEOulIYY85tTPWs4E7piQvXND/1eKUMOsdseaq9CpPngBdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-10T13:45:27Z"
    mac: ENC[AES256_GCM,data:T+5e2s+p8+SAwfqj9ikJIkXpdvMoBkRbnuoLsIhd5RFsmA5p5AqEEQx8C9C2kcfn6geBlp4BG3EXO+uARicrRLak9z0NGoxPQJgGGI1zt4ktEAfjocvCrnm73ZfEwOezRf5z85zYIcCzUvpIufoZtI72fcWojyUJGSfj+nDEFJw=,iv:pzQlpr76GFPkcHgpmjz1ZBESxfbMXnwSE5O9wjak7jY=,tag:wCYL/RbovokU/MFxjXvvsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
