# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: idp-credentials
    namespace: auth
type: Opaque
stringData:
    SECRET_AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:3AZVogN6c1rmvelyTrrnHbW6mYg4xOc=,iv:XPEQca7dj4/zYZoMJ2lhqCRTxUWIk3EhJ2WTYBtP5Mo=,tag:1STHk9ZQD4ChBSavjv4Tug==,type:str]
    SECRET_AUTHENTIK_PG_PASSWORD: ENC[AES256_GCM,data:DSIcEjtNEcP+1ccbTQg3xqB/KAs44g==,iv:LIVuB4a7BB5JpdY5Sl+DDAWmloyn418BwWlGbpM+j7M=,tag:XTY9Q43d6ubfU7eRoEBRng==,type:str]
    SECRET_AUTHENTIK_ADMIN_PASSWORD: ENC[AES256_GCM,data:nzZlTAfx1LjhBE460ADLQzjXu8Pv4w==,iv:49fJ6elALk+FoPDILIehlKStlL9amja7h8M1OaVtipg=,tag:8uFpVvnw3fe6uYWwhM5J8w==,type:str]
    SECRET_IDP_REDIS_PASSWORD: ENC[AES256_GCM,data:HaqG58AbnAgVAubHo1j4E49YhhL+Ug==,iv:sRpm7VbhdjwmpS3Awwkv7bKGj2l+YHdzlu2pCafK8Is=,tag:SIHbn8KW23UXeebKY0nMxQ==,type:str]
    SECRET_IDP_POSTGRES_PASSWORD: ENC[AES256_GCM,data:VuxaDsuhNQDLX+sapoGwkvPITI7Ryg==,iv:L8WGBoPvCp3l/OC898aqwyhXkEqpUIVQcDMz5qG9/vU=,tag:lqbDsFUtDab1KaPaYAqI+g==,type:str]
    SECRET_IDP_LDAP_USER: ENC[AES256_GCM,data:/+1ybycqsopVGdcHBNLYakr0ph0/jKzEF5afe4dI+RmFlE46wNwC1A==,iv:FyqOHYXT6ry/NloU/3fWQdXiCTBWKNCDiW9yYaqQm6c=,tag:c8AKdXMr6PB0s9cjDzQmtQ==,type:str]
    SECRET_IDP_LDAP_USER_PASSWORD: ENC[AES256_GCM,data:PqdtHa7CzQDvkWyeaWeC7ALv,iv:c7ek2fE8WyGewTNHLbqtIiGaegfuyer3+YAqrepgFNo=,tag:M8jgg+i9CtSp3FJ+J/TJNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNzBDeHg1eHdWVjlzWm1p
            L09MRlF4T0wwWlFzemdaTHdlSGF4bVduOXh3CmFkdHdNaU5ydld6ZkdyaVpPYk5u
            NGdBSnJ5UDhQTThwUFpPODk2QW5xMkUKLS0tIGdxVDJWMURFcHkya00rUWtjMktO
            YXNwb3h4OTZvUThEQXpRcm1hdlZOck0K3w+SPSHNK53odZZesd39XMWCK3Fu8ur0
            y3r2JkZnHL2UpkUvG6StlXoVoiWcHNBBiIKXLixMrU4o6y0pB5AYyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-11T20:45:20Z"
    mac: ENC[AES256_GCM,data:i2+jxQirTlM5wy2OuGOK6X3/tt0lEYA4Z1eH5yL4P8mYpupyWwc2tZzU0OgjIgwufAh2P+AFab8VtUtGMMxE0uHKnz5XXgseSzIFvZ8iB48kPEnvXdfDVTJNid1uMq3GMqrzIvi1xalEHELF7FH+4WsN6ftAg8gLuknnw4je4Cc=,iv:5ngKGVvzCicfc7UYUHKx8UiMVWw8DsvV8szbY29mM7s=,tag:/49BJNolZeBNZ19FG7kVqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
