---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky-mariadb
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: mariadb
      version: 10.3.6
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: openebs
      namespace: openebs
  values:
    env:
      TZ: Europe/Paris
    image:
      registry: ghcr.io
      repository: zcube/bitnami-compat/mariadb
      tag: 10.6
    auth:
      database: ${SECRET_BLOCKY_DB}
      username: ${SECRET_BLOCKY_DB_USER}
      password: ${SECRET_BLOCKY_DB_PASSWORD}
    primary:
      persistence:
        storageClass: openebs-jiva-csi-default
