---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.2.3
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      defaultClassReplicaCount: 2
      defaultFsType: ext4
    defaultSettings:
      defaultReplicaCount: 2
      defaultLonghornStaticStorageClass: longhorn
      replicaAutoBalance: best-effort
    ingress:
      enabled: true
      host: "longhorn.${SECRET_DOMAIN}"
      tls: true