---
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: authelia-postgres
  namespace: auth
spec:
  replicas: 2
  image: docker.io/library/postgres:14.4
  database:
    size: 10Gi
  env:
    - name: POSTGRES_PASSWORD
      value: ${SECRET_IDP_POSTGRES_PASSWORD}
    - name: POSTGRES_REPLICATION_PASSWORD
      value: ${SECRET_IDP_POSTGRES_PASSWORD}
