# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:NsCKkFJOlp93WEooVx0R7czGZttim/+g/f2z8IBpd9JNy9sHhA==,iv:hPPtolb1st62DgiRkkGhei8yIdfpmcdgkXP7ZyJc6Jc=,tag:ByH74Z/1ZBh1xYwJeSsCSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0blhCQmlHTXJMTHBDYjlW
            S3NtWmNJcW5xYUN2NHNsdGhBNjRaYkNpNXhVCm9ZTzF4a0RabzNHaTdaaTgvV3Ew
            V3poTUY0cUMrbVl0OWlnbDljWUxyY0UKLS0tIG1rQ3Q3NHNlK1JOTlNTTkQyTm0w
            c0RYRFVrcnlvN3RaK2JxUDRITHF0bnMKPFlQrT0Y7jzG+cKHaXvi5O6RxsRHZxwt
            2Nd6E8AN8GM9tqjyWmTuihySwn8XA3N/Mjl9nx22ybuzNmDmTjFMkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-10T17:54:57Z"
    mac: ENC[AES256_GCM,data:5/HjWk7rdiGVdVTw3y3phZPYWkmX1bJlM7dEaivrwb5fPeRZ0s4/daZ560UaZ6xHt2VKo5iNGtx9H2qywQqhJHa1dO/vrkWuH7C5FQyp85YYP6Q1IRLYG7bpC3wBmdRU1FvGbBACCAYtLbtx5ibLI7Ypo7kntEj4/L+e2IJ1J0Q=,iv:66Ks9Z69IZ4u9ve6tVptqLXYOHb+2mlbyRFb2WCCYhU=,tag:eNCGU4G+OazixzWxOU/Kyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
