# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:cXbXDS9WiI5QmbnyDyLM72iRfjzMDBVkbuga/LinzdH5GwVVFw==,iv:QNNrjjodttIpTj4b2uhofou+Ket3whOhkpsAWrsNBdE=,tag:fk52/SvDGbbdN5jRXW0I+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZb3piUnlBYlNpaFVicmtC
            eXU0V3BDZWVEUjNqcGs1aHhpUGFocDdicFN3CmJuUkJXTmVSWFdKazJ3L1RaMGdB
            aGNWYTFKUDNzRWhBay9pdUtBU0JiREUKLS0tIDE0Y0NhbmJJaUlDdjVoczk1Y1R0
            TGZmMmFsa29LWGxHYVQvTS83SXlobVUKLBn/vXYGmK9xXzLJ27VjkO9wPl2HvZHP
            DvbT0Q2ykJyeOvIpLnzrTmwwv3LJs/cz3YtNq66m/zD97zYEPS5mtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-18T21:10:16Z"
    mac: ENC[AES256_GCM,data:G2xNjJbtH4cAjjLubjQbznwPM13nGPclx84Uf+jlKAtiH7NR4FxoFVZyxWxF9rnMKS1aG2m3hcTFAo0AFYJndrRyzCk+PIhrAnoLnVorL2CE70zDV7+WljlGTRHevLLONxw6WYdw8fenjsuPODPiqm+qfdWIBr1lqyfMc2AbEqo=,iv:IT37CZxn+XynZH34mV0AjoopeB9VnwaH5olU/F02feo=,tag:pKz4QB3OrbncvaRFLtUk7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
