# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:dym8TNRy99VFCGxDw7vAxh2SPs5OAlGdn0pR3/HXgvLLfV/H7g==,iv:QLb4HCIgFDvw+CUZaVsVe0XWU8gZsvFS7ttdTlbM1N8=,tag:XcKQaedEUkHX9D/aqSJ5Wg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmaytnNk54OUVLVGdraWdl
            dXFSTllYakFzVk8yMzhPT2tVd3RiYmFiMXhjCkhWN09wOVBXWFpRZXlzZERiTjBv
            ZlRJN1hiMWFLR2pqK2U2Z1diait1V3MKLS0tIFZ3WmhtNGFST0ZpWCs1eWdwWjRU
            eTZEbnIxb2w0Q3NQSHlSa3BUQkI0K3MK00pCSqdVMTQPrDRFXlyD3l0eGIOwpufB
            nx/Xt+5BV+P3gVLUOt8b5yZoe9YRvTtUzlxcRkYAq6QQb1hOWlzKnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-06T17:38:02Z"
    mac: ENC[AES256_GCM,data:+ChJV4XcyZkqIb5FppCpqiQ3JHp5EKmNkiHguu20AqcTZVI2PZ2eMB+SPlDimk3abEEETXaXCeJnwfvSRlQ3CIfx+KIMHtZVWc3j6HGui67fD1ttseFzRUp7916G8x9A3kgtU23Kposf51fz2J5THVs/bWVfHfOOyAMdR6cE+iE=,iv:CbBomb5CK3S0zXit1t4JU9wvQkm71UQbdoM8uuYMRaE=,tag:sJJ4g5n7bXoLP5ouoGURdQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
